/* eslint-disable no-restricted-globals */
// This service worker implements the default offline caching strategy
// used by Create React App's PWA template. It precaches the build
// output and serves the app shell from cache on subsequent visits.

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

clientsClaim();
self.skipWaiting();

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// App shell-style routing so that all navigation requests are fulfilled
// with index.html, allowing the React router to handle the actual routing.
const handler = createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html');
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/api\//],
});
registerRoute(navigationRoute);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

