name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'frontend/public/data/*.xlsx'
      - 'frontend/public/data/*.csv'
      - 'frontend/public/data/suggested-university-mapping.json'
      # Optionally exclude other non-deployment files
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/update-rankings.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission for the contents scope

    steps:
      - name: Checkout  Git Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a recent Node.js version

      - name: Install Dependencies and Build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build # The directory containing the build output relative to the repository root 
